### ISSUE TITLE
Picture distortion being received from PicCap

### ISSUE THREAD

**Issue by UsableLoki** [TBSniller/piccap#36] opened 2022-04-22 12:25 UTC
I feel that there is some vsyncing issue with the image.  When piccap runs on the homescreen on webOS the image is fine, but then the image distorts when opening a video app or going to hdmi input.  Any idea how this can be fixed? 
![image](https://user-images.githubusercontent.com/44586220/164713720-0a13a7c9-4c65-45d1-a4bc-6630c004317c.png)

**Comment by tuxuser** [comment] 2022-05-13 08:14
Duplicate of #26. Apparently changing the resolution worked to fix it.

**Closed by tuxuser** 2022-05-13 08:14 UTC
