### ISSUE TITLE
Can't get Root Status

### ISSUE THREAD

**Issue by szbbalint** [TBSniller/piccap#32] opened 2022-02-22 21:19 UTC
Hey, i've just rooted my LG UH950V on rootmy.tv. It seems ok, installed homebrew app, and then  i have installed youtube adfree, and piccap. Youtube works ok, but piccap cant get root access. Its just loading. The only function is working is the reboot button.
In homebrew settings it says that root is ok, turned on ssh and cant access it.
I tried reinstalled piccap but not worked. After that i made a factory restet on the tv, rooted it again, installed piccap again, and nothing changed. 
I turned of that fast boot stuff in tv settings before the rooting, and checked that dev tools app is not installed.
Is there something i did wrong???
Im totally noob in that root and command line things, so please be very accurate when you give me "orders" or need something.
Thank you for reading, and the help :)

**Comment by tuxuser** [comment] 2022-02-22 23:22
Looks like a duplicate of: https://github.com/TBSniller/piccap/issues/24

**Closed** 2022-02-22 23:23 UTC
